### ISSUE TITLE
Compatibility with inkscape 1.0 and python 3

### ISSUE THREAD

**Issue by aaujon** [JarrettR/QuickJoint#10]
Hi,
Thanks for your extensions !
I started porting this extension for the upcoming version 1.0 of inkscape, it's working great when using 'tabs' creation but not yet with the slots creation.
You can see the WIP here : https://github.com/aaujon/QuickJoint, I will make a RP when it will be ready.
About the 'slots', I'm not really sure about how it should be working, for what I understand it's only working when using a simple segment, I can't easily use the feature to connect 2 rectangles for example. Don't you think that we could re-use the code that create 'tabs' to also create 'slots' by just changing a few signs ?

**Comment by JarrettR** [comment]
That's amazing, thank you!

I realise now that the explanatory gif showing slots doesn't really show how to use them very well.

The line segment is just a guide, and then should be deleted afterwards. Here's a gif I made a few years ago showing both tabs (top piece of acrylic) and slots (bottom piece)

![unnamed](https://user-images.githubusercontent.com/6027644/73476441-0e4eb680-4347-11ea-9080-98bb3073c6b7.gif)


I haven't looked at this code for a long time. I kinda remember that there was not much shared code between the two sections. I think that could be improved.

**Comment by IanSC** [comment]
thanks for the great extension.

any chance of updating the extension for Inkscape 1.0?

i tried updating it but got bogged down in:
`for id, node in self.selected.iteritems():
`
replaced with:
`for id, node in self.svg.selected.items():
`
based on the docs.
self.svg.selected is an OrderedDict.

**Comment by JarrettR** [comment]
Have you checked out @aaujon's fork?

https://github.com/aaujon/QuickJoint

I haven't used Inkscape 1.0 yet, so I don't know what the status is.

**Comment by IanSC** [comment]
it works!
thanks a lot for the help and the great plugin
