### ISSUE TITLE
Kerf isn't dealt with at all for male tabs

### ISSUE THREAD

**Issue by JarrettR** [JarrettR/QuickJoint#2]
Will probably need another checkbox for inner/outer offset of the kerf

**Comment by oscaracena** [comment]
This is still an Issue. Kerf is ignored in tabs, and this is vital for wall joints.

**Comment by JarrettR** [comment]
I haven't had regular access to a laser cutter in the last year, happy to accept pull requests @oscaracena

**Comment by oscaracena** [comment]
Oh, thanks. I have access to a K-40 and I'm willing to help. Any tip for where to start digging (in the code)?

Btw, with slots, I'm having some strange behavior. If I set kerf to 0, the joints fit but a little loose. I want a tighter fit, so I've changed the lower limit (in order to allow negative kerfs). Using -0.20, the fit is perfect and tight. Maybe you know why this happens. 

Thanks for your time!

**Comment by JarrettR** [comment]
Sounds like a normal laser cutter fit issue - My laser was around 0.14mm - 0.17mm kerf, so it's in the right ballpark. The reason that's happening for you is that the laser controller is trying to cut directly on the line you sent to it, but the laser beam itself is not infinitely small. In your case, it's cutting around 0.1mm on either side of the line. By setting kerf to -0.2mm, you're telling the laser to cut slightly to the left or the right of the line, so that the physical dimensions of the final piece end up where you want (and the waste piece has even more material cut out of it).

For changes, the kerf compensation will have to be added to this section:
https://github.com/JarrettR/QuickJoint/blob/master/quickjoint.py#L183

The vertical portions will have to move left or right, depending on which side of the tab it's on, and the bottom of the valleys and tops of hills will also have to move up or down.

The distance to move will be kerf / 2, like here: https://github.com/JarrettR/QuickJoint/blob/master/quickjoint.py#L90
This is because we only care about the laser diameter on one half of the target line.

**Comment by JarrettR** [comment]
Solved in #15

**Comment by oscaracena** [comment]
Thanks @JarrettR for fixing this, and also for the response you gave me. It's a great job!
