### ISSUE TITLE
Please update to newer Inkscape verion (1.3). thx

### ISSUE THREAD

**Issue by JoanMCD** [JarrettR/QuickJoint#21]
Please update to newer Inkscape verion (1.3). thx

**Comment by JarrettR** [comment]
Tested with 1.3, still works

**Comment by JoanMCD** [comment]
Thx for testing. I tried all your docu-exampes and I ever get a error box...

_C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:65: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-s", "--side",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:69: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-n", "--numtabs",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:73: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-l", "--numslots",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:77: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-t", "--thickness",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:81: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-k", "--kerf",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:85: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-u", "--units",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:89: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-e", "--edgefeatures",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:93: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-f", "--flipside",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:97: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-a", "--activetab",
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:345: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:307: DeprecationWarning: Effect.unittouu is now a method in the SvgDocumentElement class. Use `self.svg.unittouu(str)` instead.
  self.thickness = self.unittouu(str(self.options.thickness) + self.options.units)
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:308: DeprecationWarning: Effect.unittouu is now a method in the SvgDocumentElement class. Use `self.svg.unittouu(str)` instead.
  self.kerf = self.unittouu(str(self.options.kerf) + self.options.units)
C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py:314: DeprecationWarning: Effect.selected is now a dict in the SvgDocumentElement class. Use `self.svg.selected`.
  for id, node in self.selected.iteritems():
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py", line 345, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\deprecated\deprecatedeffect.py", line 220, in affect
    return self.run(args=args)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 250, in run
    self.save_raw(self.effect())
  File "C:\Users\...\AppData\Roaming\inkscape\extensions\QuickJoint-0.92\quickjoint.py", line 314, in effect
    for id, node in self.selected.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'_

**Comment by JoanMCD** [comment]
OK - found the problem - the version from Github work. 
Thx for the tool ! :-)
