### ISSUE TITLE
RE: QuickJoint and InkScape 0.92

### ISSUE THREAD

**Issue by silver2row** [JarrettR/QuickJoint#8]
Hello,

I tried to use this repo for promoting edges w/ tabs in InkScape 0.92. I put the .inx file and .py file in the extensions folder in the inkscape folder.

...

I also tried to put the extension in %appdata%\inkscape but I have been unsuccessful thus far. Have you updated your repo in a while or do things need to happen to set up things again?

Seth

P.S. If you are busy, I understand. If you are working on this project still and do not want people bothering you about it, that is cool too. Please reply if/and/or/but. Either way, I will wait to hear from you.

**Comment by JarrettR** [comment]
On this install of Windows, I installed Inkscape through the Windows App Store, which is pretty annoying with regard to permissions, barring me from easily being able to get into the Inkscape folder.

Follow these directions and see if they work for you, then I'll update the readme:


To install, in Inkscape, go to `Edit > Preferences > System` and take note of the `User extensions` folder.

On my machine, it was `C:\Users\Jarrett\AppData\Roaming\inkscape\extensions` and I had to create the `inkscape\extensions` folders myself, due to the way I'd installed Inkscape.

Copy the two main files, `quickjoint.inx` and `quickjoint.py` into that folder, and restart Inkscape.

**Comment by silver2row** [comment]
Hello,

Thank you. I should have known. I will try the app on Win 10. Oh and I will try the install w/ Inkscape first w/ Edit > Preferences > System.

...

The `Edit > Preferences > System` section on the Inkscape software worked when I used the extensions section file path and added the .inx file and .py file.

Seth

P.S. Thank you, sir. I tested it. It works. The software you made works fine now. I must have been just using the incorrect file location for your .inx and .py files.

**Comment by silver2row** [comment]
Hello Sir,

Please hold off on posting the update. Let me try some stuff first. I thought I had it fixed b/c I got it to work. Let me rearrange the files and directories and try again. I cannot make it work again for some reason.

Seth

**Comment by silver2row** [comment]
Hello,

I was mistaken on what I need to do to make this source work. I think it is an inkscape feature that does not allow for squares or rectangles w/ this source.

...

I know I am not making much sense b/c I do not know exactly what needs to happen for me to make a couple of tabs on the end. 

Seth

P.S. I am sure your source works fine. I am just not getting the desired outcome thus far. My issue, not your issue.

**Comment by JarrettR** [comment]
Gotcha.

If you make a rectangle, it is a special type of object - After you create it, select the rectangle and go to `Path->Object To Path`

From there, it will be a regular SVG path that this extension will work on. That's worth mentioning in the Readme, I will add it.

**Comment by silver2row** [comment]
Hello Sir,

I found it once and got it to work only once. Let me settle down and try to explain things here.

...

`C:\Users\Filster\AppData\Roaming\inkscape\extensions` is where I put the .py and .inx files. 

I used a normal rectangle like I did the first time. I tried w/ and w/out the `PATH > Object to Path` option in the drop down menu.

...

I think either I am making an easy thing complicated or I am just wrong thus far.

Seth

**Comment by silver2row** [comment]
Hello Once More,

I think I have some unmet dependencies. I will try to update my machine and from that point forward, I will then reply.

Seth

**Comment by silver2row** [comment]
Hello...I am not going to get DIA or pstoedit. I think, from my extension error file, these two modules are what my system needs but I am not going to get it right now.

Seth

P.S. Sorry for bothering you. I guess I am just making mistakes over here.
