### ISSUE TITLE
Does not work in InkScape 0.92.4

### ISSUE THREAD

**Issue by vmario89** [JarrettR/QuickJoint#9]
Hi, this extensions looks interesting but it simply does no output in InkScape 0.92.4 on Windows. I dont see anything strange in .py file and i dont get any error.

**Comment by JarrettR** [comment]
Have you selected a path object before running the extension?

Keep in mind that boxes are not paths - You'd need to convert it with the `Path->Object to Path` command

**Comment by vmario89** [comment]
sorry my fault. I misunderstood the usage of this. Now i got it. I am closing this issue. Thanks for the cool tool!
by the way there is something similar called "Path To Flex" -> https://github.com/thierry7100/Path2flex

![grafik](https://user-images.githubusercontent.com/5631071/68701087-57803d00-0586-11ea-8a17-2fe4ad270460.png)
